    INI
    .DB  87
    INI
    .DB  219
    INI
    .DB  128
    INI
    .DB  230
    INI
    .DB  1
    INI
    .DB  40
    INI
    .DB  250
    INI
    .DB  237
    INI
    .DB  162
    INI
    .DB  32
    INI
    .DB  246
    INI
    .DB  203
    INI
    .DB  124
    INI
    .DB  40
    INI
    .DB  242
    INI
    .DB  96
    INI
    .DB  20
    INI
    .DB  122
    INI
    .DB  211
    INI
    .DB  130
    INI
    .DB  254
    INI
    .DB  16
    INI
    .DB  32
    INI
    .DB  233
    INI
    .DB  175
    INI
    .DB  211
    INI
    .DB  130
    INI
    .DB  195
    INI
    .DB  0
    INI
    .DB  0

